import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Header from "@/components/Header";
import localFont from "next/font/local";
import Provider from "./Provider";
import MobileMenu from "@/components/MobileMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazir = localFont({
  src: [
    {
      path: "../../public/fonts/Vazir-Thin-FD.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/Vazir-Light-FD.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/Vazir-FD.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Vazir-Medium-FD.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Vazir-Bold-FD.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-vazir",
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={vazir.variable}>
      <body className="bg-[#FBFBFB]  h-full overflow-x-hidden relative pb-40">
        <Provider>
          <div className="flex flex-col items-center w-full  relative h-full">
          <Header />
          <main className="container mx-auto px-2 xl:px-4 ">{children}</main>
          </div>
          <MobileMenu/>
        </Provider>
      </body>
    </html>
  );
}
